<?php
/**
 * Created by PhpStorm.
 * User: unochapeco
 * Date: 16/04/18
 * Time: 19:21
 */

namespace Application\Controller;


use Application\Entity\User;
use Doctrine\ORM\EntityManager;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\JsonModel;
use Zend\View\Model\ViewModel;
use \Application\Validator\User as UserValidator;

class PessoasController extends AbstractActionController
{
    protected $em;

    protected $userService;

    public function __construct(EntityManager $em, \Application\Service\User $userService)
    {
        $this->em = $em;
        $this->userService = $userService;
    }

    public function indexAction()
    {
        $page = $this->params()->fromQuery('page', 1);
        $users = $this->userService->pagination($page);

        return new ViewModel(['users' => $users]); // TODO: Change the autogenerated stub
    }

    public function showAction()
    {
        $id = $this->params()->fromRoute('id',0);

        die("show $id");

    }

    public function createAction()
    {
        $request = $this->getRequest();
        $erros = ['email' => [], 'name' => []];

        if ($request->isPost()) {
            $values = $request->getPost();
            $validator = new UserValidator();
            $validator->setData($values);

            if ($validator->isValid()) {
                $data = $validator->getValues();
            } else {
                $erros = $validator->getMessages();
            }


        }

       return new ViewModel(['errors' => $erros]);

    }

    public function updateAction()
    {
        die("Update");

    }

    public function deleteAction()
    {
        die("Action Delete");
    }


}